"""
Report figures for Milestone 6.
File location: <project_root>/src/models/figures.py

Every figure is generated from a metrics dict, so nothing in your report is
hand-drawn and everything can be regenerated by one command.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.models.metrics import normalised_confusion

PALETTE = ["#4C72B0", "#DD8452", "#55A868", "#C44E52", "#8172B3"]


# ---------------------------------------------------------------------------
def plot_confusion_matrices(
    cm: Sequence[Sequence[int]],
    class_names: Sequence[str],
    out_path: Path,
    title: str = "",
) -> None:
    """Raw counts and row-normalised, side by side.

    Both are needed. The raw matrix is dominated by class 0 and makes the rare
    classes invisible; the normalised one (each row = per-class recall) shows
    that the model may be getting most of the rare cases wrong.
    """
    cm = np.asarray(cm, dtype=int)
    cm_norm = normalised_confusion(cm)
    n = len(class_names)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.4))

    for ax, matrix, fmt, name, cmap in (
        (axes[0], cm, "d", "Counts", "Blues"),
        (axes[1], cm_norm, ".2f", "Row-normalised (per-class recall)", "Blues"),
    ):
        im = ax.imshow(matrix, cmap=cmap, vmin=0,
                       vmax=matrix.max() if matrix.max() > 0 else 1)
        ax.set_title(name, fontsize=10)
        ax.set_xticks(range(n)); ax.set_yticks(range(n))
        ax.set_xticklabels(class_names, rotation=35, ha="right", fontsize=8)
        ax.set_yticklabels(class_names, fontsize=8)
        ax.set_xlabel("Predicted"); ax.set_ylabel("True")

        threshold = matrix.max() / 2 if matrix.max() > 0 else 0.5
        for i in range(n):
            for j in range(n):
                value = matrix[i, j]
                ax.text(j, i, format(value, fmt), ha="center", va="center", fontsize=8,
                        color="white" if value > threshold else "black")
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    fig.suptitle(title or "Confusion matrix (test split)", fontsize=11)
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
def plot_per_class_recall(
    all_metrics: List[Dict[str, Any]],
    class_names: Sequence[str],
    out_path: Path,
) -> None:
    """Per-class recall for every architecture, grouped by class.

    This is where the imbalance shows: expect a tall bar for No DR and short
    ones for Mild and Severe, across all three models.
    """
    n = len(class_names)
    x = np.arange(n)
    width = 0.8 / max(len(all_metrics), 1)

    fig, ax = plt.subplots(figsize=(9.5, 4.8))
    for i, (metrics, colour) in enumerate(zip(all_metrics, PALETTE)):
        recalls = [pc["recall"] for pc in metrics["per_class"]]
        ax.bar(x + i * width - 0.4 + width / 2, recalls, width,
               label=metrics.get("backbone", metrics.get("run_name")),
               color=colour, edgecolor="black", linewidth=0.5)

    supports = [pc["support"] for pc in all_metrics[0]["per_class"]]
    ax.set_xticks(x)
    ax.set_xticklabels([f"{name}\n(n={s})" for name, s in zip(class_names, supports)],
                       fontsize=8)
    ax.set_ylabel("Recall (sensitivity)")
    ax.set_ylim(0, 1.05)
    ax.set_title("Per-class recall on the test split")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.25, linestyle=":")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------------
def plot_roc_curves(
    y_true: np.ndarray,
    probabilities: np.ndarray,
    class_names: Sequence[str],
    out_path: Path,
    title: str = "",
) -> None:
    """One-vs-rest ROC curve per class, with AUC in the legend."""
    from sklearn.metrics import auc, roc_curve

    y_true = np.asarray(y_true)
    fig, ax = plt.subplots(figsize=(6.6, 6))

    for label, (name, colour) in enumerate(zip(class_names, PALETTE)):
        binary = (y_true == label).astype(int)
        if binary.min() == binary.max():
            continue                      # class absent from this split
        fpr, tpr, _ = roc_curve(binary, probabilities[:, label])
        ax.plot(fpr, tpr, color=colour, linewidth=1.8,
                label=f"{label} {name} (AUC {auc(fpr, tpr):.3f})")

    ax.plot([0, 1], [0, 1], "k--", linewidth=1, alpha=0.5, label="chance")
    ax.set_xlabel("False positive rate")
    ax.set_ylabel("True positive rate")
    ax.set_title(title or "One-vs-rest ROC curves (test split)")
    ax.legend(fontsize=8, loc="lower right")
    ax.grid(alpha=0.25, linestyle=":")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------------
def plot_error_distance(
    error_stats: Dict[str, Any],
    out_path: Path,
    title: str = "",
) -> None:
    """How far off the wrong answers are.

    The story this tells: most errors are off by one grade, which is why QWK
    stays high while plain accuracy looks unremarkable. Ordinal errors are not
    all equal, and this figure is the evidence.
    """
    counts = error_stats["error_distance_counts"]
    distances = sorted(counts)
    values = [counts[d] for d in distances]
    total = sum(values)

    fig, ax = plt.subplots(figsize=(7, 4.2))
    colours = ["#55A868"] + ["#DD8452"] * (len(distances) - 1)
    bars = ax.bar([str(d) for d in distances], values,
                  color=colours[: len(distances)], edgecolor="black", linewidth=0.6)
    for bar, value in zip(bars, values):
        if value:
            ax.annotate(f"{value}\n({value/total:.1%})",
                        xy=(bar.get_x() + bar.get_width() / 2, bar.get_height()),
                        xytext=(0, 3), textcoords="offset points",
                        ha="center", fontsize=8)

    ax.set_xlabel("|predicted grade − true grade|   (0 = correct)")
    ax.set_ylabel("Number of test images")
    ax.set_title(title or "Error magnitude on the test split")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------------
def plot_model_comparison(comparison: pd.DataFrame, out_path: Path) -> None:
    """Headline metrics for the three architectures, side by side."""
    metrics = [("QWK", "QWK"), ("accuracy", "Accuracy"),
               ("balanced_acc", "Balanced acc."), ("F1_macro", "Macro F1")]

    fig, axes = plt.subplots(1, len(metrics), figsize=(15, 4.2), sharey=True)
    for ax, (col, label) in zip(axes, metrics):
        if col not in comparison.columns:
            ax.axis("off"); continue
        ax.bar(comparison["backbone"], comparison[col],
               color=PALETTE[: len(comparison)], edgecolor="black", linewidth=0.6)
        for i, value in enumerate(comparison[col]):
            ax.text(i, value + 0.012, f"{value:.3f}", ha="center", fontsize=8)
        ax.set_title(label, fontsize=10)
        ax.set_ylim(0, 1.05)
        ax.tick_params(axis="x", rotation=25, labelsize=8)
        ax.grid(axis="y", alpha=0.25, linestyle=":")
        ax.spines[["top", "right"]].set_visible(False)

    fig.suptitle("Architecture comparison on the held-out test split", fontsize=11)
    fig.tight_layout(rect=[0, 0, 1, 0.93])
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
